name: radovid

services:
  radovid:
    container_name: radovid
    command: "air -c .air.toml"
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: .
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
